Update SonarQube.yml

diff --git a/.github/workflows/SonarQube.yml b/.github/workflows/SonarQube.yml
--- a/.github/workflows/SonarQube.yml
+++ b/.github/workflows/SonarQube.yml
@@ -52,8 +52,6 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python }}
-      - name: Install tox and any other packages
-        run: pip install tox
       - name: Run python test
         if: always()
         run: |
@@ -68,10 +66,10 @@ jobs:
             coverage run -m pytest
             coverage xml -i
             echo "Checking if coverage directory exists..."
-            ls -l coverage || echo "❌ Coverage folder not found"
+            ls -l coverage.xml || echo "❌ Coverage folder not found"
             cd ../
             echo "Checking if coverage directory exists..."
-            ls -l ./api/coverage || echo "❌ Coverage folder not found"
+            ls -l ./api/coverage.xml || echo "❌ Coverage folder not found"
       - name: 🔍 Run SonarCloud Scan
         uses: sonarsource/sonarcloud-github-action@v2
         env:
